<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.5 on darwin)" generated="20200922 07:44:48.913" rpa="false">
<suite id="s1" name="API Tests" source="/Users/anrisawada/20projects/robot-scripts/example/Tests/API_Tests.robot">
<test id="s1-t1" name="Make a simple REST API call">
<kw name="Check Github Username" library="Github">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>my_github_session</arg>
<arg>https://api.github.Comment</arg>
</arguments>
<msg timestamp="20200922 07:44:49.172" level="INFO">Creating Session using : alias=my_github_session, url=https://api.github.Comment, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20200922 07:44:49.172" endtime="20200922 07:44:49.172"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>my_github_session</arg>
<arg>users/robotframeworktutorial</arg>
</arguments>
<assign>
<var>${response}</var>
</assign>
<msg timestamp="20200922 07:44:49.216" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103530e50&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.423" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103530f40&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.826" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103514cd0&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.845" level="FAIL">ConnectionError: HTTPSConnectionPool(host='api.github.comment', port=443): Max retries exceeded with url: /users/robotframeworktutorial (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x1035ab190&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))</msg>
<status status="FAIL" starttime="20200922 07:44:49.173" endtime="20200922 07:44:49.845"></status>
</kw>
<status status="FAIL" starttime="20200922 07:44:49.171" endtime="20200922 07:44:49.846"></status>
</kw>
<tags>
<tag>API</tag>
</tags>
<status status="FAIL" starttime="20200922 07:44:49.171" endtime="20200922 07:44:49.846" critical="yes">ConnectionError: HTTPSConnectionPool(host='api.github.comment', port=443): Max retries exceeded with url: /users/robotframeworktutorial (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x1035ab190&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))</status>
</test>
<test id="s1-t2" name="Display emoji from Github">
<kw name="Display Emoji" library="Github">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>my_github_session</arg>
<arg>https://api.github.Comment</arg>
</arguments>
<msg timestamp="20200922 07:44:49.847" level="INFO">Creating Session using : alias=my_github_session, url=https://api.github.Comment, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20200922 07:44:49.847" endtime="20200922 07:44:49.848"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>my_github_session</arg>
<arg>emojis</arg>
</arguments>
<assign>
<var>${response}</var>
</assign>
<msg timestamp="20200922 07:44:49.851" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05a90&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
<msg timestamp="20200922 07:44:50.054" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05bb0&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
<msg timestamp="20200922 07:44:50.457" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05d30&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
<msg timestamp="20200922 07:44:50.460" level="FAIL">ConnectionError: HTTPSConnectionPool(host='api.github.comment', port=443): Max retries exceeded with url: /emojis (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05e80&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))</msg>
<status status="FAIL" starttime="20200922 07:44:49.848" endtime="20200922 07:44:50.460"></status>
</kw>
<status status="FAIL" starttime="20200922 07:44:49.847" endtime="20200922 07:44:50.461"></status>
</kw>
<tags>
<tag>API</tag>
</tags>
<status status="FAIL" starttime="20200922 07:44:49.846" endtime="20200922 07:44:50.461" critical="yes">ConnectionError: HTTPSConnectionPool(host='api.github.comment', port=443): Max retries exceeded with url: /emojis (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05e80&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))</status>
</test>
<doc>These are some API tests</doc>
<status status="FAIL" starttime="20200922 07:44:48.915" endtime="20200922 07:44:50.462"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="2">API</stat>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="API Tests">API Tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200922 07:44:49.216" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103530e50&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.423" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103530f40&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.826" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103514cd0&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /users/robotframeworktutorial</msg>
<msg timestamp="20200922 07:44:49.851" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05a90&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
<msg timestamp="20200922 07:44:50.054" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05bb0&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
<msg timestamp="20200922 07:44:50.457" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x103e05d30&gt;: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /emojis</msg>
</errors>
</robot>
